appearance_feature_extractor_params:
  image_channel: 3
  block_expansion: 64
  num_down_blocks: 2
  max_features: 512
  reshape_channel: 32
  reshape_depth: 16
  num_resblocks: 6

motion_extractor_params:
  num_kp: 21

warping_module_params:
  num_kp: 21
  block_expansion: 64
  max_features: 512
  num_down_blocks: 2
  reshape_channel: 32
  estimate_occlusion_map: true
  dense_motion_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    reshape_depth: 16
    compress: 4

context_decoder_params:
  upscale: 2
  block_expansion: 64
  max_features: 512
  num_down_blocks: 2
